### ISSUE TITLE
Update the Readme

### ISSUE THREAD

**Issue by darshansharma** [darshansharma/CricHere#2]
update the readme

**Comment by SofiaHerrera27** [comment]
Hello, I would like to help contribute to your project in this issue.

**Comment by darshansharma** [comment]
> Hello, I would like to help contribute to your project in this issue.

Go ahead and contribute.

**Comment by SofiaHerrera27** [comment]
Hello, I would like to help contribute to your project in this issue.
I accidentally removed it and took away my assignment.
